export const FIRST_FORM_DATA = 'FIRST_FORM_DATA';
export const SECOND_FORM_DATA = 'SECOND_FORM_DATA';
export const THIRD_FORM_DATA = 'THIRD_FORM_DATA';
export const FINAL_FORM_DATA = 'THIRD_FORM_DATA';